### ISSUE TITLE
Re-subscription on each startup

### ISSUE THREAD

**Issue by rustychris** [axiom-data-science/docker-erddap#1]
I'm invoking the container like this

```
 docker run \ 
     -p 80:8080 \
     -p 443:8443 \
     -v /path/on/host/erddap_config:/opt/tomcat/content/erddap \
     -v /path/on/host/erddapData:/erddapData \
     -v /path/on/host/data:/rawData \
     --name erddap \
     axiom/docker-erddap
```

And subsequently starting it with `sudo docker start -ai erddap`

Each time I edit datasets.xml and restart like this, I get a flood of emails to verify subscriptions.  In my previous, non-docker, installation, this only happened once.  This leads me to think that some aspect of the ERDDAP state isn't being persisted.  

p.s. thanks for making this repo available - very helpful!

**Comment by kwilcox** [comment]
Interesting, thanks for the report. Can you share your `datasets.xml` and `setup.xml` as gists?

**Comment by rustychris** [comment]
Here is a gist with datasets.xml and setup.xml.  Most of the problematic datasets are set to active="false"

https://gist.github.com/rustychris/cab004950a1dd611d01a2f1c76a49cae

**Comment by kwilcox** [comment]
@rustychris I just pushed version `1.74`, could you give this a try again? Please note it is based on `unidata/tomcat-docker` now so the mount points have changed a bit. `/opt/tomcat` is now `/usr/local/tomcat` in the container.

**Comment by kwilcox** [comment]
Of course, please wait until the builds are done... https://hub.docker.com/r/axiom/docker-erddap/builds/

**Comment by kwilcox** [comment]
Over a year, no reply, closing.
