### ISSUE TITLE
font error and JAVA_HOME

### ISSUE THREAD

**Issue by n-a-t-e** [axiom-data-science/docker-erddap#10]
I'm getting an error when running this image after building fresh with no cached images. anyone else run into this? 

```
...
bufferedImage isAccelerated=[unknown]
ERROR during ERD Low Level Startup:
ERROR while initializing SgtGraph:
java.lang.RuntimeException: ERROR in SgtUtil.getFont: Bitstream Vera Sans not available.
Java 1.8.0_242 (64 bit, Oracle Corporation) on Linux (4.19.76-linuxkit).
Fonts available: DejaVu Sans, DejaVu Sans Mono, DejaVu Serif, Dialog, DialogInput, Monospaced,
  SansSerif, Serif
 at com.cohort.util.Test.error(Test.java:41)
 at gov.noaa.pfel.coastwatch.sgt.SgtUtil.getFont(SgtUtil.java:122)
 at gov.noaa.pfel.coastwatch.sgt.SgtGraph.<init>(SgtGraph.java:93)
 at gov.noaa.pfel.erddap.util.EDStatic.<clinit>(EDStatic.java:1806)
 at gov.noaa.pfel.erddap.Erddap.<init>(Erddap.java:214)
```

It seems that java is no longer looking for fonts in `/usr/local/openjdk-8/lib/fonts/` ?

It works if we switch from `${JAVA_HOME}/lib/fonts/` to `${JAVA_HOME}/jre/lib/fonts/` in the Dockerfile

**Comment by kwilcox** [comment]
Thanks @n-a-t-e!

I've been meaning to update the fonts to use the [DeJaVu fonts](https://coastwatch.pfeg.noaa.gov/erddap/download/DejaVuFonts.zip) that ERDDAP now suggests over the BitStream fonts. Would you be interested in including that in your PR?

See https://coastwatch.pfeg.noaa.gov/erddap/download/setup.html (search DeJaVu) for more info.

**Comment by n-a-t-e** [comment]
@kwilcox Sure!

**Comment by kwilcox** [comment]
Interesting... the ERDDAP docs want us to download the DeJaVu fonts but they are built into the JDK base the repo is using. Do the graph fonts show up from your locally built image fine?

**Comment by n-a-t-e** [comment]
Yep the graphs and other pages look good to me!

In the docs it also says   _With Linux AdoptOpenJDK Java distributions: DejaVu fonts are built in,  so you don't have to do separately install them._ 

Not sure if we are using AdoptOpenJDK but the Dejavu fonts are in the list in the error error message above

**Comment by kwilcox** [comment]
We are, this is the base image: https://github.com/Unidata/tomcat-docker/blob/b9c533c43ec8c063305365a808323e5d86b83dd7/Dockerfile#L4

Thanks!
