### ISSUE TITLE
fontFamily remains in image

### ISSUE THREAD

**Issue by ebridger** [axiom-data-science/docker-erddap#13]
Re: #10 . No sure how this happens but  the erddap2.02 image on docker hub did not seem to get this fix to the server.xml file.  It remains `<fontFamily>Bitstream Vera Sans</fontFamily>`. Note this effects the https://github.com/ioos/erddap-gold-standard as well, which is where I first noticed this.

**Comment by kwilcox** [comment]
Are you using the `latest` image tag? To avoid version drift and keep backwards compat I did not update the 2.02 image tag.

**Comment by ebridger** [comment]
No. Explicitly used the 2.02 tag. Have a lot of containers still using 1.82, with the "latest" tag. I'm not very familiar with docker hub and don't understand why latest and 2.02 images should be different?

**Comment by kwilcox** [comment]
For this docker image (and many others but certainly not all or a majority of them), the `master` branch in git is equal to the `latest` image tag in the docker repository. [Git tags](https://github.com/axiom-data-science/docker-erddap/releases) have an equivalent docker image tag as well. It is good practice to use an actual image tag (i.e. `2.02`) when running the image so you can be sure it's going to stay on that version. If you use the `latest` tag you run the risk of introducing a new image version. Sometimes (like in this case) introducing a new version is what you want so you can use the `latest` docker image tag.

You will need to `docker pull axiom/docker-erddap:latest` to download the most recent `latest` tag. If you `docker run` from a machine that already has a tag it will not check for newer versions of the same tag.

**Comment by ebridger** [comment]
O.K.  'latest' tag is not advertised here or on docker hub.  And the 2.02 image fails to start erddap.  I'll switch to trying 'latest' and re tag my 1.82 image.  See if that fixes things.

**Comment by ebridger** [comment]
That did fix things.  Thanks.
