### ISSUE TITLE
allow to boost needed memory by setting environment variable

### ISSUE THREAD

**Issue by marc-portier** [axiom-data-science/docker-erddap#28]
the current setenv.sh script hardcodes the needed memory to 4G

would be nice if we could inject that from outside the container
as simple change to setenv.sh should do the trick

``` 
MEMORY=${ERDDAP_MEMORY:-4G}
```

**Comment by kwilcox** [comment]
:+1: care to submit a PR supporting `ERDDAP_MIN_MEMORY` and `ERDDAP_MAX_MEMORY`?
