### ISSUE TITLE
Update to ERDDAP 2.12

### ISSUE THREAD

**Issue by abkfenris** [axiom-data-science/docker-erddap#30]
Or apparently scheduled Github Actions time out if there isn't enough activity on a repo.

<img width="904" alt="image" src="https://user-images.githubusercontent.com/1296209/119563507-a14e0400-bd75-11eb-90f7-ffebbbc825e0.png">

**Comment by kwilcox** [comment]
:roll_eyes: I pushed the button. Thanks!  https://github.com/axiom-data-science/docker-erddap/issues/30

**Comment by abkfenris** [comment]
Danke! I'd love to figure out a fuller test suite and then automate update PRs at some point, maybe using  ioos/erddap-gold-standard with more datasets?

Enjoy the release notes!
