### ISSUE TITLE
Docker server not working as expected when on remote host

### ISSUE THREAD

**Issue by RoryMMMM** [axiom-data-science/docker-erddap#35]
I'm deploying this container to a VM running on my local machine with the end goal of having this eventually run on a production server. I'm seeing an issue where if I try to access the container using the VM's host name I get some problems.

* I start the container using `docker run -d --env ERDDAP_MIN_MEMORY=1G --env ERDDAP_MAX_MEMORY=2G -p 9090:8080 axiom/docker-erddap` Port 8080 is already in use on this machine but 9090 isn't. This pulls the latest image from docker-hub.
* If I navigate to "https://docker-machine:9090/erddap/index.html" I see the expected page. A couple of the pictures are broken but the bulk is there. 
* If I click on any of the HTML links on the page I get redirected to "localhost:8080". So clicking on "show me all datasets" takes me to "http://localhost:8080/erddap/info/index.html?page=1&itemsPerPage=1000"
* Taking a look at the image details shows that they're trying to be pulled from loclahost:8080/erddap/images as well. 
* I've tried some of the older tags as well but I run into memory issues since the default is stuck at 4G (and my VM is really small) for those ones and the environment variable config seems to be new. 

Any ideas on what's going on? I'm rather new to Tomcat so my experience is lacking.

**Comment by RoryMMMM** [comment]
I see that this is covered in the erddap config file "setup.xml" as "MUST CHANGE" variables. It might be good to mention this in the readme.

**Comment by kwilcox** [comment]
Thanks @RoryMMMM. It is a fine line between what we document in this repository and what is already documented in the ERDDAP documentation. We don't want to diverge so have always sided that users will reference the ERDDAP documentation when questions arise.

https://github.com/axiom-data-science/docker-erddap/pull/42 changes the way the container is configured by default and provides a list of recommended options to change, which seems to cover your request!
