### ISSUE TITLE
Tag "2.14" missing

### ISSUE THREAD

**Issue by aded** [axiom-data-science/docker-erddap#37]
Hi all,
thanks for containerizing ERDDAP! :-)

it seems a Docker image tagged "2.14" is missing. "latest" is actually the v2.14, but please note that tag is usually a sort of pointer to a versioned image (2.14 in this case).
In a prod environment, it's a common practice to freeze an image to a specific version, rather than using "latest".

**Comment by kwilcox** [comment]
There is now a 2.14 tag [here](https://hub.docker.com/layers/axiom/docker-erddap/2.14/images/sha256-b78654e20db88533faf9b3089f1a3969ae75288cebc5058e27e4e5cb34698de9?context=explore) which uses the patched upstream tomcat image (log4j fixes).
