### ISSUE TITLE
Unexpected end of file on DasDds.sh

### ISSUE THREAD

**Issue by rsignell-usgs** [axiom-data-science/docker-erddap#4]
My dockerized ERDDAP instance is a testing ground, so yesterday I wanted to try a new dataset and I just deleted my old `datasets.xml` with 600 datasets, and created a new `datasets.xml` with just the one new dataset.   

When I log into the container and run `/usr/local/tomcat/webapps/erddap/WEB-INF/DasDds.sh`, I get this error:
```
*** DasDds ***
This generates the DAS and DDS for a dataset and puts it in
/erddapData/logs/DasDds.out
Press ^D or ^C to exit at any time.

Which datasetID (default="")
? obspy
WARNING: regexDelete says: "/erddapData/dataset/py/obspy/" isn't a directory.
dataset dir=/erddapData/dataset/py/obspy/
dataset n files not deleted = 0

*** DasDds obspy

EDD.oneFromDatasetsXml(obspy)...

*** An error occurred while trying to load obspy:
java.lang.Exception: ERROR in XML file on line #1: Unexpected end of
file while looking for end of first tag="".
```

**Comment by rsignell-usgs** [comment]
I sent my `datasets.xml` file to @BobSimons, and he said it worked fine, and suggested verifying whether this was really being used by the container.    Sure enough, although the volume mounted `datasets.xml` was fine, the `datasets.xml` in the container was empty (zero size).

Stopping and restarting the container fixed the problem. 

@kwilcox, any idea what I might have done wrong, so I could prevent this from happening again?

**Comment by kwilcox** [comment]
If you are going to delete and remake the datasets.xml file on your host you are going to have to restart the container.

**Comment by rsignell-usgs** [comment]
So if I want to make changes to datasets.xml, I should login to the container and make them?   I've been modifying the datasets.xml on the host and it's been working fine.  Or is it just if I remove it altogether?

**Comment by kwilcox** [comment]
You should make them on the host and then restart the container.
