### ISSUE TITLE
ERDDAP_emailSmtpPort ignored

### ISSUE THREAD

**Issue by aded** [axiom-data-science/docker-erddap#46]
Hello,

when I set SMTP port through env var, the value is ignored (587, Google account):
```
  ERDDAP_emailSmtpPort: "587"
```
`log.txt`:
```
********** ERRORS **********
Error: Sending email to XXX failed: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.googlemail.com, 25; timeout -1;
  nested exception is:
        java.net.ConnectException: Connection timed out (Connection timed out)
```

If I set the value in `setup.xml`:
```
<emailSmtpPort>587</emailSmtpPort>
```
things work correctly.

**Comment by kwilcox** [comment]
When the container starts and prints out its configuration, does it include `ERDDAP_emailSmtpPort: "587"` in the case where you are setting via environmental variable?

**Comment by aded** [comment]
> When the container starts and prints out its configuration, does it include `ERDDAP_emailSmtpPort: "587"` in the case where you are setting via environmental variable?

Well, the variable is set actually, if I `docker inspect`:
```
            "Env": [
(...)
                "ERDDAP_emailSmtpPort=587",
(...)
            ],
```
And of course I got the same value when the container starts:
```
ERDDAP configured with: ERDDAP_CONTENT_URL=https://github.com/BobSimons/erddap/releases/download/v2.18/erddapContent.zip
(...)
ERDDAP_emailSmtpPort=587
(...)
```
Indeed I was wondering if this is an "erddap" or a "docker-erddap" issue...

**Comment by kwilcox** [comment]
Without debugging it does appear to be an ERDDAP issue. The support for using those environmental variables comes from ERDDAP. Try quoting the value? Maybe it is a type error somewhere in the code?

**Comment by aded** [comment]
> Without debugging it does appear to be an ERDDAP issue. The support for using those environmental variables comes from ERDDAP. Try quoting the value? Maybe it is a type error somewhere in the code?

Hi Kyle,
thanks for your answers.

Yes the value is quoted. I've opened an issue on ERDDAP repo too.

**Comment by srstsavage** [comment]
As noted on the [ERDDAP issue](https://github.com/BobSimons/erddap/issues/78), this was due to a bug in int and bool env var processing in ERDDAP itself. It is fixed in this commit:

https://github.com/BobSimons/erddap/commit/63526dca6016ab4944e3469f86a7d7a17ecbfc83#diff-7ecb16bc02b7390a29326c3e6039ebab6fea2db6a316296cac29db3e2a03baa9

and will be fixed in the next ERDDAP release. A workaround until then is to set the env var without the `ERDDAP_` prefix (so `emailSmtpPort` instead of `ERDDAP_emailSmtpPort`.
