### ISSUE TITLE
Rebase on unidata/tomcat-docker:8.5-jdk11-openjdk?

### ISSUE THREAD

**Issue by joefutrelle** [axiom-data-science/docker-erddap#47]
Anecdotally, running ERDDAP under JDK 11 may address some performance issues with RAM consumption. If this is the case, would it be possible to rebase this image on that tag?

I can investigate further and report back if that would be helpful in assessing this potential change.

**Comment by srstsavage** [comment]
Introduced #49 which would make it easier to build this image based on various base images, including `unidata/tomcat-docker:8.5-jdk11-openjdk`. If it gets merged we can look at publishing image variants to Docker Hub.

**Comment by kwilcox** [comment]
@joefutrelle FYI the PR has been merged and you can now build a container yourself using the build argument. As Shane said we will look into publishing under different base images.

**Comment by joefutrelle** [comment]
That's great, thanks @kwilcox

**Comment by abkfenris** [comment]
@kwilcox what if we published image variants to Github container registry?

**Comment by joefutrelle** [comment]
I ran a build based on the jdk11 tomcat image and so far everything seems to be running fine.

**Comment by kwilcox** [comment]
Thanks Joe, I added a PR to build the JDK11 images as well and push to the registry

**Comment by kwilcox** [comment]
@joefutrelle [`axiom/docker-erddap:latest-jdk11-openjdk`](https://hub.docker.com/layers/docker-erddap/axiom/docker-erddap/latest-jdk11-openjdk/images/sha256-c96578170a7cc856b9cde80ccd1b660161db6d7f7cd7302fa7728b43cb0f07c1?context=explore) is available now, let me know if you have any trouble!
