### ISSUE TITLE
Unable to run image on Apple Silicon/M1 Mac

### ISSUE THREAD

**Issue by popovs** [axiom-data-science/docker-erddap#69]
Hello, when trying to pull this docker image via Dockerhub I get the following error: "no matching manifest for linux/arm64/v8 in the manifest list of entries."

So I came here and cloned the repo via Github. To get it to run on my computer I had to amend the line in Read Me/Quickstart to:

```
docker run --platform linux/x86_64 -d -p 8080:8080 axiom/docker-erddap:latest-jdk17-openjdk
```

Not sure if there's anything you can update from within the docker image to fix this, but hopefully this is helpful to anyone else who may have this issue.

**Comment by abkfenris** [comment]
Hi @popovs, thank you for the `--platform linux/x86_64` incantation as I'm about to experience the same issue with a new machine.

If you are using `docker compose`, [`platform: linux/x86/64`](https://docs.docker.com/compose/compose-file/05-services/#platform) should do the trick within the service definition.

Unfortunately, the ERDDAP image is built on [unidata/tomcat-docker](https://hub.docker.com/r/unidata/tomcat-docker) which is single architecture, so we won't be able to make it multi architecture without a bigger rebuild.

**Comment by srstsavage** [comment]
@popovs When convenient, can you test out one of the new arm/v8 images?

axiom/docker-erddap:2.23-jdk17-openjdk
axiom/docker-erddap:latest-jdk17-openjdk

They work for me locally under emulation but I don't have an actual M* mac to test hardware.
