### ISSUE TITLE
Newest release missing linux/amd64

### ISSUE THREAD

**Issue by callumrollo** [axiom-data-science/docker-erddap#87]
I cannot pull the latest docker image. Using the command from the README `docker run -d -p 8080:8080 axiom/docker-erddap:latest-jdk21-openjdk` returns:

`docker: no matching manifest for linux/amd64 in the manifest list entries`

On the axiom docker-erddap repo, the jkd21 image is only available for linux/arm64, despite the Docker file stating on line 2:

`#referencing a specific image digest pins our unidata tomcat-docker image to platform amd64 (good)`

Is dropping support for amd64 in favour of arm64 intentional?

**Comment by callumrollo** [comment]
Note: this could very likely be user error! I'm not a docker expert

It also seems that the older images are no longer available. I can no longer pull `axiom/docker-erddap:2.22-jdk17-openjdk` which we were using in production last year. I get error

`Error response from daemon: manifest for axiom/docker-erddap:2.22-jdk17-openjdk not found: manifest unknown: manifest unknown`

 If older images are being removed from axiom/docker-erddap repo that could cause problems. As currently I'm only able to pull the `2.23-jdk17-openjdk` image, which is not the latest release.

**Comment by srstsavage** [comment]
Yikes, I updated the GitHub Action which builds and pushes the images so must have messed up something there. I manually pushed both platforms for `axiom/docker-erddap:2.24-jdk21-openjdk` and will look into fixing the automated build.

I did clean up some older images, I'll make sure to keep at least the last few versions available in the future.

**Comment by srstsavage** [comment]
I refactored GHA and believe this is now fixed. Issue was that GHA matrix approach doesn't play nice with docker multi-platform builds.
